name: Validate PR Develop Branch
on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - force-app/**
    branches:
      - main
jobs:
  validate-pr-develop-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "14"
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

        #Installing npm so that sfdx can be installed  
      - name: Install npm
        run: npm install


      - name: Install Salesforce CLI
        run: |
          npm install @salesforce/cli --global